package com.ziroom.framework.ferrari.test.entity;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.util.Date;


@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ContractLabelEntity implements Serializable {
    /**
     * Database Column Remarks:
     * 自增字段
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_label.id
     *
     * @mbg.generated Tue Dec 22 16:28:45 CST 2020
     */
    private Long id;

    /**
     * Database Column Remarks:
     * 收房合同ID
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_label.hire_contract_id
     *
     * @mbg.generated Tue Dec 22 16:28:45 CST 2020
     */
    private Long hireContractId;

    /**
     * Database Column Remarks:
     * 是否支持尾房，0-不支持，1-支持
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_label.support_tail
     *
     * @mbg.generated Tue Dec 22 16:28:45 CST 2020
     */
    private Integer supportTail;

    /**
     * Database Column Remarks:
     * 标签版本
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_label.version_code
     *
     * @mbg.generated Tue Dec 22 16:28:45 CST 2020
     */
    private String versionCode;

    /**
     * Database Column Remarks:
     * 创建时间-触发时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_label.create_time
     *
     * @mbg.generated Tue Dec 22 16:28:45 CST 2020
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     * 更新时间
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_label.last_modify_time
     *
     * @mbg.generated Tue Dec 22 16:28:45 CST 2020
     */
    private Date lastModifyTime;

    /**
     * Database Column Remarks:
     * 本表记录是否删除,@1-删除@0-未删除
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_label.is_del
     *
     * @mbg.generated Tue Dec 22 16:28:45 CST 2020
     */
    private Integer isDel;

    /**
     * Database Column Remarks:
     * 是否支持一房两价，0-不支持，1-支持
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contract_label.support_one_room_two_price
     *
     * @mbg.generated Tue Aug 16 16:28:45 CST 2021
     */
    private Integer supportReduce;
}